language: go

go:
  - 1.6.3

install:
  - go get "github.com/sec51/qrcode"
  - go get "github.com/Traverse-Care/cryptoengine"
  - go get "github.com/sec51/convert/smallendian"

script:
  - go test -v ./...
